language: elixir
elixir:
  - 1.3.0
  - 1.2.5
otp_release:
  - 18.3
notifications:
  recipients:
    - adam@apathydrive.com
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test
after_success:
  - "mix compile && mix coveralls.travis"
env:
  - MIX_ENV=test
